=== SuziAI/gui-tools/json_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Song Dynasty Notation Music Piece",
  "description": "Digital representation of a Song dynasty music piece (this includes Lülüpu, Gongchepu and Suzipu notations)",
  "type": "object",
  "properties": {
    "version": {
      "description": "The version number of the notation format used by the piece.",
      "type": "string"
    },
    "notation_type": {
      "description": "The notation type the piece uses, it must be either 'Suzipu', 'Lvlvpu' or 'Gongchepu'.",
      "type": "string",
      "enum": [
        "Suzipu",
        "Lvlvpu",
        "Gongchepu"
      ]
    },
    "composer": {
      "description": "The piece's composer.",
      "type": "string"
    },
    "mode_properties": {
      "description": "The properties referring to the mode of the piece.",
      "type": "object",
      "properties": {
        "gong_lvlv": {
          "description": "The Lülü pitch corresponding to the mode's 宫.",
          "type": "integer",
          "minimum": 0,
          "maximum": 10
        },
        "final_note": {
          "description": "The mode's final note, must be either '宫', '商', '角', '变', '徵', '羽', or '闰'",
          "type": "string",
          "enum": [
            "宫",
            "商",
            "角",
            "变",
            "徵",
            "羽",
            "闰"
          ]
        }
      }
    },
    "images": {
      "description": "This field contains the list of relative paths to the image files belonging to the piece in the right order.",
      "type": "array",
      "items": {
        "type": "string",
        "description": "Relative path to the image file."
      }
    },
    "content": {
      "description": "List of all boxes corresponding to the individual semantic unities of the piece, e.g., title characters, preface characters, or musical information boxes containing the lyrics and notational information.",
      "type": "array",
      "items": {
        "type": "object",
        "description": "Properties of a single box.",
        "properties": {
          "box_type": {
            "description": "The annotation type of the box, i.e., 'Title', 'Mode', 'Preface', 'Music', or 'Unmarked.",
            "type": "string",
            "enum": [
              "Title",
              "Mode",
              "Preface",
              "Music",
              "Lyrics",
              "Unmarked"
            ]
          },
          "is_excluded_from_dataset": {
            "description": "If true, when exporting the image dataset from the corpus, this box is not included. This is advisable if the image data in the box is distorted by artifacts or the annotation content does not fit to the image content.",
            "type": "boolean"
          },
          "is_line_break": {
            "description": "If true, the box is taken to be the last box before a column break.",
            "type": "boolean"
          },
          "text_coordinates": {
            "description": "The segmentation box coordinates (upper left and lower right corners) for textual information, including lyrics.",
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "description": "The point's x and y coordinates.",
              "type": "array",
              "minItems": 2,
              "maxItems": 2,
              "items": {
                "type": "integer",
                "minimum": 0
              }
            }
          },
          "text_content": {
            "description": "The textual content of the box. A text-based box may contain up to one Chinese character.",
            "type": "string"
          },
          "notation_coordinates": {
            "description": "The segmentation box coordinates (upper left and lower right corners) for notational information.",
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "description": "The point's x and y coordinates.",
              "type": "array",
              "minItems": 2,
              "maxItems": 2,
              "items": {
                "type": "integer",
                "minimum": 0
              }
            }
          },
          "notation_content": {
            "description": "The notational content of the box. A notational box may contain a suzipu-describing string like '0;'. This should only be filled for boxes of type 'Music'.",
            "type": "string"
          }
        },
        "required": [
          "box_type"
        ]
      }
    },
    "additionalProperties": false
  },
  "additionalProperties": false,
  "required": [
    "version",
    "notation_type",
    "composer",
    "mode_properties",
    "content"
  ]
}

=== SuziAI/gui-tools/tutorial/01_geximeiling.json
{"version": "1.0", "notation_type": "Suzipu", "composer": "\u59dc\u5914", "mode_properties": {"gong_lvlv": 8, "final_note": "\u7fbd"}, "content": [{"box_type": "Title", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[902, 211], [957, 278]], "text_content": "\u9b32"}, {"box_type": "Title", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[898, 276], [960, 341]], "text_content": "\u6eaa"}, {"box_type": "Title", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[900, 342], [960, 407]], "text_content": "\u6885"}, {"box_type": "Title", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[899, 407], [959, 475]], "text_content": "\u4ee4"}, {"box_type": "Mode", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[923, 486], [962, 533]], "text_content": "\u4ed9"}, {"box_type": "Mode", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[932, 542], [961, 593]], "text_content": "\u5442"}, {"box_type": "Mode", "is_excluded_from_dataset": false, "is_line_break": true, "text_coordinates": [[917, 609], [962, 662]], "text_content": "\u8abf"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[833, 275], [884, 335]], "text_content": "\u4e19"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[836, 342], [890, 400]], "text_content": "\u8fb0"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[836, 405], [888, 469]], "text_content": "\u51ac"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[838, 469], [886, 531]], "text_content": "\u81ea"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[830, 531], [892, 591]], "text_content": "\u7121"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[829, 596], [889, 666]], "text_content": "\u932b"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[831, 670], [891, 730]], "text_content": "\u6b78"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[829, 731], [887, 791]], "text_content": "\u4f5c"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[829, 792], [891, 852]], "text_content": "\u6b64"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[831, 855], [887, 923]], "text_content": "\u5bd3"}, {"box_type": "Preface", "is_excluded_from_dataset": false, "is_line_break": true, "text_coordinates": [[826, 923], [888, 995]], "text_content": "\u610f"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[635, 23], [693, 79]], "text_content": "\u597d", "notation_coordinates": [[713, 21], [751, 83]], "notation_content": "5."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[635, 77], [692, 142]], "text_content": "\u82b1", "notation_coordinates": [[713, 98], [749, 144]], "notation_content": "9"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[639, 145], [689, 203]], "text_content": "\u4e0d", "notation_coordinates": [[711, 159], [753, 203]], "notation_content": "7"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[636, 211], [694, 269]], "text_content": "\u8207", "notation_coordinates": [[713, 224], [747, 276]], "notation_content": "5#"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[638, 273], [692, 329]], "text_content": "\u6ba2", "notation_coordinates": [[714, 290], [750, 330]], "notation_content": "0"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[637, 332], [695, 394]], "text_content": "\u9999", "notation_coordinates": [[710, 346], [752, 394]], "notation_content": "4"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[641, 398], [695, 448]], "text_content": "\u4eba", "notation_coordinates": [[715, 405], [743, 464]], "notation_content": "5."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[640, 461], [694, 519]], "text_content": "\u6d6a", "notation_coordinates": [[715, 473], [749, 525]], "notation_content": "C."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[636, 529], [694, 589]], "text_content": "\u7cbc", "notation_coordinates": [[712, 537], [746, 590]], "notation_content": "E"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[638, 590], [694, 648]], "text_content": "\u7cbc", "notation_coordinates": [[712, 595], [750, 647]], "notation_content": "C."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[641, 650], [695, 708]], "text_content": "\u53c8", "notation_coordinates": [[716, 662], [748, 698]], "notation_content": "4"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[643, 709], [691, 771]], "text_content": "\u6050", "notation_coordinates": [[716, 718], [744, 760]], "notation_content": "5"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[637, 776], [695, 840]], "text_content": "\u6625", "notation_coordinates": [[711, 781], [749, 826]], "notation_content": "C"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[639, 842], [695, 900]], "text_content": "\u98a8", "notation_coordinates": [[715, 849], [743, 887]], "notation_content": "9"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[635, 903], [691, 976]], "text_content": "\u6b78", "notation_coordinates": [[713, 917], [751, 959]], "notation_content": "7"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[634, 974], [694, 1032]], "text_content": "\u53bb", "notation_coordinates": [[712, 980], [752, 1036]], "notation_content": "5."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[633, 1031], [693, 1097]], "text_content": "\u7da0", "notation_coordinates": [[710, 1049], [752, 1093]], "notation_content": "4z"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[637, 1096], [696, 1163]], "text_content": "\u6210", "notation_coordinates": [[713, 1105], [751, 1151]], "notation_content": "2"}, {"box_type": "Music", "is_excluded_from_dataset": true, "is_line_break": true, "text_coordinates": [[637, 1161], [694, 1217]], "text_content": "\u9670", "notation_coordinates": [[715, 1164], [750, 1218]], "notation_content": "0#"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[501, 21], [559, 81]], "text_content": "\u7389", "notation_coordinates": [[578, 32], [618, 72]], "notation_content": "4"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[500, 85], [560, 137]], "text_content": "\u923f", "notation_coordinates": [[579, 96], [617, 144]], "notation_content": "7"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[502, 143], [560, 203]], "text_content": "\u4f55", "notation_coordinates": [[579, 151], [613, 211]], "notation_content": "5#"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[503, 204], [559, 276]], "text_content": "\u8655", "notation_coordinates": [[576, 218], [615, 260]], "notation_content": "4z"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[499, 273], [558, 345]], "text_content": "\u5c0b", "notation_coordinates": [[578, 274], [618, 330]], "notation_content": "5."}, {"box_type": "Music", "is_excluded_from_dataset": true, "is_line_break": false, "text_coordinates": [[508, 347], [556, 381]], "text_content": "", "notation_coordinates": [[576, 348], [618, 383]], "notation_content": ""}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[503, 392], [559, 457]], "text_content": "\u6728", "notation_coordinates": [[577, 404], [612, 469]], "notation_content": "5."}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[502, 455], [556, 524]], "text_content": "\u862d", "notation_coordinates": [[574, 469], [620, 515]], "notation_content": "9"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[500, 522], [556, 590]], "text_content": "\u96d9", "notation_coordinates": [[579, 528], [619, 574]], "notation_content": "7"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[506, 589], [556, 649]], "text_content": "\u69f3", "notation_coordinates": [[578, 592], [620, 648]], "notation_content": "5#"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[506, 648], [557, 715]], "text_content": "\u5922", "notation_coordinates": [[578, 659], [618, 701]], "notation_content": "9"}, {"box_type": "Music", "is_excluded_from_dataset": false, "is_line_break": false, "text_coordinates": [[506, 720], [555, 771]], "text_content": "\u4e2d", "notation_coordinates": [[575, 714],
